### ISSUE TITLE
Consider "namespacing" the plugin

### ISSUE THREAD

**Issue by x80486** [Jax-p/vite-plugin-nunjucks#10]
I've seen that all plugins are somehow "namespaced" (I call it like that because I don't know what's the correct term) to the author/company. I think this one could make use of the same trend, so it's not confusing to find it between the vast `npm` space — something like `@jax-p/vite-plugin-nunjucks` :thinking:

**Comment by Jax-p** [comment]
Thank you for feedback. I named it according to the [Vite documentation](https://vitejs.dev/guide/api-plugin.html)
> Vite Plugins should have a clear name with **vite-plugin-** prefix.
