### ISSUE TITLE
It doesn't work. nunjucks is not a function

### ISSUE THREAD

**Issue by kalininmax** [Jax-p/vite-plugin-nunjucks#12]
![image](https://user-images.githubusercontent.com/20542636/213574118-3bbeb0e3-b75a-45f0-859d-b37414e3fcb9.png)
![image](https://user-images.githubusercontent.com/20542636/213573838-6de3f371-59cb-473e-a3e1-ce1059b6a30f.png)
![image](https://user-images.githubusercontent.com/20542636/213573930-e56b5e29-ea02-4901-b3fa-b5afc81fc14b.png)

**Comment by Kaito23** [comment]
+ 1
I just tried https://github.com/vituum/vite-plugin-nunjucks instead. Maybe this is outdated. 
(I am new to vite)

**Comment by Jax-p** [comment]
Sorry I've been pretty busy to look on this because I did not use Vite for a long time. Any help would be aprpiciated / PR would be reviewed.

**Comment by AzA-95** [comment]
I send PR for fix this https://github.com/Jax-p/vite-plugin-nunjucks/pull/13

**Comment by AzA-95** [comment]
Before this is merged, you can use in the vite.config.js plugins **nunjucks.default**

**See picture below**

![Снимок](https://user-images.githubusercontent.com/52655410/223235729-a614547b-3388-41d2-b54e-29887b0b512f.PNG)

**Comment by Jax-p** [comment]
https://github.com/Jax-p/vite-plugin-nunjucks/pull/13 tyvm!
