### ISSUE TITLE
Upgrading to Vite 5

### ISSUE THREAD

**Issue by zuramai** [Jax-p/vite-plugin-nunjucks#14]
Hi, thank you for making such a great library!

After Vite 5 was out in recent week, I think it is possible to upgrade to Vite 5. My project is still working as usual, but it's giving deprecation warning:

```bash
$ vite
vite v5.0.2 building for production...
plugin 'nunjucks' uses deprecated 'enforce' option. Use 'order' option instead.
plugin 'nunjucks' uses deprecated 'transform' option. Use 'handler' option instead.
```

**Comment by Jax-p** [comment]
https://github.com/Jax-p/vite-plugin-nunjucks/pull/15 tyvm!
