### ISSUE TITLE
When do you use this plugin?

### ISSUE THREAD

**Issue by notflip** [Jax-p/vite-plugin-nunjucks#9]
I'm wondering when one has the need for this plugin?

**Comment by Kaito23** [comment]
If you want to use the template engine nunjucks :)
https://mozilla.github.io/nunjucks/

**Comment by notflip** [comment]
Aha so this plugin parses nunjucks templates with the Vite build tool, is that it?

**Comment by Kaito23** [comment]
Yes :) It should. But it seems to be broken. See #12 (this was why I am here :D)

**Comment by Jax-p** [comment]
#12
